language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler -v 1.10.6
bundler_args: --deployment
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec
env:
  global:
    - secure: "e5JCro8/ftd7DLmhT5TO0D7A2ijsiobDMCp/wvngY09iof/kvYeNHsRMeRZWBi4fMzpEWgdMqIm8Y9TH3xByB0Pe5E8PjZsgceWniVZfKZAkTigH1xuZGx9Emump0sBy6gKe7QSAz6G6Eq58vZf3xiQLFcCM5Rv8tDheWo+UGtn1haRgLKDOOa+chXyUIUphdbazy2JUpbsWHmotddlrtiGNgIYo2e7Rvod1SccNdPUc4F/gzyR6CC+bmbHvIhk9x85k0OgV679m+Hv9677/2rkTvjRhZErTzdIml1LSWXaLmA+UTzrYnp9EndZDggdXxB1XgPM2s59nV8nmws0JT2ReXNNKbPpjyI3vkb04FOroyFuXVO1T5PNe+jMBzJ6I9noRBWjVPn0e+ocal0Av5cwN+6kYm64giwhReawc996YHQkuFFWeBWEhhfG/Uwl263/OKE71KT8iVahLuVy1vxU/Ecc7aE2ADk11eZUCj/2qzAudD/rRymXwz11er/ik8U5qG0DdPmh+IIBv1ewwrrjZFFIw5n/b4DHf9EbNLxByGyHk4MBFp0m1ERNvhV4sipejGFD2wLiI048WfNb3daElD8bpGddixoVy93jZ1sBzfGJVLIiZdoZpBe5h0LCJbmV95f98DDLH1uICjTzf9u0ghgGB9PKqkWD2yKF6Mk0="
