language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler -v 1.10.6
bundler_args: --deployment
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec
env:
  global:
    - secure: secure: "CL0hGicWEnbf1XpVMCbn9FuI4zxWQXT/UrX/OPmxpnjWHbQNZw5QqfkTrFnEcfXgSMVK4Wj1YgR4RBbXuOpMg0gV3zPNhQtmZr8+0EVZE3zGbtUOtyKkgNCmdeEMDColBGnifuVkrcjiiLQv2cBiMLTfBK9cBvtX+vTrHt8WV7PICkD0h+6fq6QG2A7p8nXTutkvGlZntSbzrJmVmOMt0kwAsf5YiU3yNsUhNftf/7s4+JO3mGGhM+ItBawkPMDN52l26Uz1DaX7h6jZvEeOCfzZPryDxmdJm21boBOwXb9RfJtof4rkN1aDLf7DmTgh0puvGStdvRaQfowSyE6CQbiLjnp/ljgvrLbbkxv4GYZUgVy8vMC39DWkRbrBqsM2slT4y4KQHR8TmkpcxapS1/LYWLAcXbJuAf5elRrzmMucAUS2/oH6tfQcyNbUG6nkng3kEY+dwDtia2XsCO4PU2amC9KuQ5NJlaMSvXrz/uBLsBN1nZivp5yCkrlk4vRnznvualBOa2Co0+kJF299xvT4dE2buI0l8c6Klvv0i8jk+9YM324K9Rx8NdIPI8OEYMOwzPOP2ALj/5bAyL5X8AsvkmuZ2gA+VB851kCmku8z8RK7gQBTrbAOz4TOMVPp5Em9/34RW1jbqahBoOGsu80br7P6gYZpO3hyY7J2/Vc="
